/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Admin;
import model.Employees;
import model.Products;
import model.Stocklog;
import model.Stocklog2;
import model.Updates;
import service.AdminService;
import service.EmployeeService;
import service.ProductService;
import service.UpdatesService;

/**
 *
 * @author GANZA
 */
public class AdmGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdmGUI
     */
    public AdmGUI() {
        initComponents();
          addItemCombo();
        addProductItemList();
    }
    private void addItemCombo() {
    try {
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 5000);
        AdminService service = (AdminService) theRegistry.lookup("admin");
        List<Admin> theAdmins = service.allAdmin();

        admincombo.removeAllItems(); // Clear existing items

        if (theAdmins != null ) {
            for (Admin admin : theAdmins) {
                admincombo.addItem(admin);
            }
        } else {
            // Handle the case where theAdmins is null or empty
            System.out.println("No admin data available.");
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}
private DefaultListModel<Products> listModel=new DefaultListModel<Products>();
  private void addProductItemList(){
      try{
          Registry theRegistry=LocateRegistry.getRegistry("127.0.0.1",5000);
          ProductService service=(ProductService) theRegistry.lookup("product");
          List<Products> products=service.allProducts();
            for(Products theProduct : products){
               listModel.addElement(theProduct);
            }
            productListItem.setModel(listModel);
      }catch(Exception ex){
         ex.printStackTrace();
      }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        dutyTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        regBtn = new javax.swing.JButton();
        selAllBtn = new javax.swing.JButton();
        logOuTEBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        SearchETxt = new javax.swing.JTextField();
        updTxt = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        resetEBtn = new javax.swing.JButton();
        bImageTxt = new javax.swing.JLabel();
        searchEBtn = new javax.swing.JButton();
        admincombo = new javax.swing.JComboBox<Admin>();
        jScrollPane2 = new javax.swing.JScrollPane();
        productListItem = new javax.swing.JList<Products>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        adidTxt = new javax.swing.JTextField();
        namesTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        admPassTxt = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        searchidTxt = new javax.swing.JTextField();
        searchAdmBtn = new javax.swing.JButton();
        logoutAdm = new javax.swing.JButton();
        regAdmBtn = new javax.swing.JButton();
        updAdmTxt = new javax.swing.JButton();
        delAdmTxt = new javax.swing.JButton();
        seleAlBtn = new javax.swing.JButton();
        resetABtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updatesTxt = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        uplogoutBtn = new javax.swing.JButton();
        dateTxt = new com.toedter.calendar.JDateChooser();
        resetUpd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        selectAllBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pidTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        searchProductBtn = new javax.swing.JButton();
        pnameTxt = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JTextField();
        cpTxt = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        spTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(153, 255, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("EMPLOYEES INFORMATION");

        jLabel13.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel13.setText("First Name");

        jLabel14.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel14.setText("Last Name");

        jLabel15.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel15.setText("Duty");

        jLabel16.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel16.setText("Amount Earned");

        lnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTxtActionPerformed(evt);
            }
        });

        dutyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dutyTxtActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel17.setText("Password");

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        regBtn.setBackground(new java.awt.Color(0, 0, 0));
        regBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        regBtn.setForeground(new java.awt.Color(255, 255, 0));
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        selAllBtn.setBackground(new java.awt.Color(0, 0, 0));
        selAllBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selAllBtn.setForeground(new java.awt.Color(255, 255, 0));
        selAllBtn.setText("Select All");
        selAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selAllBtnActionPerformed(evt);
            }
        });

        logOuTEBtn.setBackground(new java.awt.Color(0, 0, 0));
        logOuTEBtn.setForeground(new java.awt.Color(255, 255, 0));
        logOuTEBtn.setText("LOGOUT");
        logOuTEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOuTEBtnActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel26.setText("Search Employee ID");

        SearchETxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchETxtActionPerformed(evt);
            }
        });

        updTxt.setBackground(new java.awt.Color(0, 0, 0));
        updTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updTxt.setForeground(new java.awt.Color(255, 255, 0));
        updTxt.setText("Update");
        updTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updTxtActionPerformed(evt);
            }
        });

        delBtn.setBackground(new java.awt.Color(0, 0, 0));
        delBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delBtn.setForeground(new java.awt.Color(255, 255, 0));
        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchETxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(updTxt)
                .addGap(18, 18, 18)
                .addComponent(delBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(SearchETxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updTxt)
                            .addComponent(delBtn))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        resetEBtn.setBackground(new java.awt.Color(0, 0, 0));
        resetEBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetEBtn.setForeground(new java.awt.Color(255, 255, 0));
        resetEBtn.setText("Reset");
        resetEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEBtnActionPerformed(evt);
            }
        });

        searchEBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchEBtn.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        searchEBtn.setForeground(new java.awt.Color(255, 255, 0));
        searchEBtn.setText("Search");
        searchEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(productListItem);

        jLabel34.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel34.setText("Admin");

        jLabel35.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel35.setText("Product");

        print.setBackground(new java.awt.Color(0, 0, 0));
        print.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 0));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(regBtn))
                            .addComponent(jLabel35))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(searchEBtn)
                                .addGap(18, 18, 18)
                                .addComponent(selAllBtn)
                                .addGap(34, 34, 34)
                                .addComponent(print)
                                .addGap(18, 18, 18)
                                .addComponent(resetEBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(292, 292, 292))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel34))
                        .addGap(136, 136, 136)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(salaryTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(admincombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                                .addComponent(bImageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dutyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(logOuTEBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bImageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel14))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(dutyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(admincombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(selAllBtn)
                                            .addComponent(resetEBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(print)
                                            .addComponent(regBtn)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchEBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOuTEBtn))
        );

        jTabbedPane1.addTab("Employess", jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 51));
        jLabel19.setText("ADMINISTRATOR  INFORMATION");

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel20.setText("ADID");

        jLabel21.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel21.setText("Names");

        jLabel23.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel23.setText("Username");

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel24.setText("Password");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Search By ID");

        searchAdmBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchAdmBtn.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        searchAdmBtn.setForeground(new java.awt.Color(255, 255, 0));
        searchAdmBtn.setText("Search");
        searchAdmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel29)
                .addGap(30, 30, 30)
                .addComponent(searchidTxt)
                .addGap(18, 18, 18)
                .addComponent(searchAdmBtn)
                .addGap(109, 109, 109))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(searchidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAdmBtn))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        logoutAdm.setBackground(new java.awt.Color(0, 0, 0));
        logoutAdm.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        logoutAdm.setForeground(new java.awt.Color(255, 255, 0));
        logoutAdm.setText("LOGOUT");
        logoutAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdmActionPerformed(evt);
            }
        });

        regAdmBtn.setBackground(new java.awt.Color(0, 0, 0));
        regAdmBtn.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        regAdmBtn.setForeground(new java.awt.Color(255, 255, 51));
        regAdmBtn.setText("Register");
        regAdmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAdmBtnActionPerformed(evt);
            }
        });

        updAdmTxt.setBackground(new java.awt.Color(0, 0, 0));
        updAdmTxt.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        updAdmTxt.setForeground(new java.awt.Color(255, 255, 0));
        updAdmTxt.setText("Update");
        updAdmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updAdmTxtActionPerformed(evt);
            }
        });

        delAdmTxt.setBackground(new java.awt.Color(0, 0, 0));
        delAdmTxt.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        delAdmTxt.setForeground(new java.awt.Color(255, 255, 0));
        delAdmTxt.setText("Delete");
        delAdmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAdmTxtActionPerformed(evt);
            }
        });

        seleAlBtn.setBackground(new java.awt.Color(0, 0, 0));
        seleAlBtn.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        seleAlBtn.setForeground(new java.awt.Color(255, 255, 0));
        seleAlBtn.setText("Select all");
        seleAlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleAlBtnActionPerformed(evt);
            }
        });

        resetABtn.setBackground(new java.awt.Color(51, 51, 51));
        resetABtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resetABtn.setForeground(new java.awt.Color(255, 255, 0));
        resetABtn.setText("Reset");
        resetABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetABtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel23)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(48, 48, 48)))
                            .addComponent(jLabel24))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(admPassTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(namesTxt)
                            .addComponent(usernameTxt)
                            .addComponent(adidTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(logoutAdm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(regAdmBtn)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updAdmTxt)
                                .addGap(26, 26, 26)
                                .addComponent(delAdmTxt)
                                .addGap(38, 38, 38)
                                .addComponent(seleAlBtn)
                                .addGap(28, 28, 28)
                                .addComponent(resetABtn))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel20))
                            .addComponent(adidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))
                    .addComponent(namesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(admPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regAdmBtn)
                        .addComponent(delAdmTxt)
                        .addComponent(seleAlBtn)
                        .addComponent(updAdmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resetABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel25)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(logoutAdm)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel10)
                .addGap(177, 630, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel10)
                .addContainerGap(598, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setText("Updates to Employees");

        jLabel28.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel28.setText("Date");

        jLabel30.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel30.setText("Announcement");

        updatesTxt.setColumns(20);
        updatesTxt.setRows(5);
        jScrollPane1.setViewportView(updatesTxt);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel32.setText("Click");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("here");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel33.setText("to see Employees opinions/ requests");

        uplogoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        uplogoutBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        uplogoutBtn.setForeground(new java.awt.Color(255, 255, 0));
        uplogoutBtn.setText("LOGOUT");
        uplogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplogoutBtnActionPerformed(evt);
            }
        });

        resetUpd.setBackground(new java.awt.Color(0, 0, 0));
        resetUpd.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        resetUpd.setForeground(new java.awt.Color(255, 255, 0));
        resetUpd.setText("RESET");
        resetUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetUpdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                                .addComponent(resetUpd))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel27))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel32)
                        .addGap(6, 6, 6)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)))
                .addGap(179, 179, 179))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(uplogoutBtn)
                .addGap(282, 282, 282))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel28)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(resetUpd))
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jButton3)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uplogoutBtn)
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("Updates", jPanel8);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Trajan Pro 3", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("PRODUCTS INFORMATION");

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel3.setText("Product Name");

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel1.setText("Purchase Price/CP");

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel8.setText("Selling Price/SP");

        registerBtn.setBackground(new java.awt.Color(0, 0, 0));
        registerBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 0));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        selectAllBtn.setBackground(new java.awt.Color(0, 0, 0));
        selectAllBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectAllBtn.setForeground(new java.awt.Color(255, 255, 0));
        selectAllBtn.setText("Select All");
        selectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        logOutBtn.setForeground(new java.awt.Color(255, 255, 0));
        logOutBtn.setText("LOGOUT");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel18.setText("Search Product ID");

        pidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidTxtActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 0));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 0));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(pidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn))
                        .addGap(2, 2, 2))
                    .addComponent(jLabel18))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        resetBtn.setBackground(new java.awt.Color(0, 0, 0));
        resetBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 0));
        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        searchProductBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchProductBtn.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        searchProductBtn.setForeground(new java.awt.Color(255, 255, 0));
        searchProductBtn.setText("Search");
        searchProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductBtnActionPerformed(evt);
            }
        });

        quantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(registerBtn)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addComponent(searchProductBtn)
                                            .addGap(73, 73, 73)
                                            .addComponent(selectAllBtn)
                                            .addGap(58, 58, 58)
                                            .addComponent(resetBtn))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2)
                                                .addComponent(cpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(spTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(190, 190, 190)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addComponent(pnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(logOutBtn)))
                .addGap(0, 177, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(registerBtn)
                                .addComponent(searchProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(selectAllBtn)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logOutBtn))))
        );

        jTabbedPane1.addTab("Products", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
//     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//    String dDate = sdf.format(ddateTxt.getDate());
//    String eDate = sdf.format(edateTxt.getDate());

    try {
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 5000);
        ProductService service = (ProductService) theRegistry.lookup("product");
        Products theproduct = new Products();
       // java.util.Date fromDate = edateTxt.getDate();
                    
//        java.util.Date toDate = ddateTxt.getDate();
        //dates
//               java.util.Date fromDate = edateTxt.getDate();
//        java.util.Date toDate = ddateTxt.getDate();
//        
//            if (fromDate != null && toDate != null) {
//            LocalDate currentDate = LocalDate.now();
//            LocalDate chosenFromDate = fromDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//            LocalDate chosentoDate = toDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//
//            if (chosentoDate.isAfter(currentDate)) {
//                JOptionPane.showMessageDialog(this, "Please choose a date that is not in the future");
//               
//            }else if(chosenFromDate.isBefore(currentDate)){
//            JOptionPane.showMessageDialog(this,"Enter a date that is not is past");
//           
//            } }

             if (pnameTxt.getText().trim().isEmpty() || !nameCheck(pnameTxt.getText())) {
            JOptionPane.showMessageDialog(this, "Product name is Mandatory and should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
        }  else if (quantityTxt.getText().trim().isEmpty() || !isInteger(quantityTxt.getText()) || !isQuantityValid(Integer.parseInt(quantityTxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Product quantity is Mandatory and should be greater than 0", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
        }
//        else if (ddateTxt.getDate() == null || edateTxt.getDate() == null) {
//            JOptionPane.showMessageDialog(this, "Delivery date and Expiry date are Mandatory", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
//        } 
        else if (cpTxt.getText().trim().isEmpty() || !isInteger(cpTxt.getText())) {
            JOptionPane.showMessageDialog(this, "Product CP is Mandatory and should be an integer", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
        } else if (spTxt.getText().trim().isEmpty() || !isInteger(spTxt.getText())) {
            JOptionPane.showMessageDialog(this, "Product SP is Mandatory and should be an integer", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
        } else {
            theproduct.setpName(pnameTxt.getText());
           // theproduct.setpId(Integer.valueOf(pidTxt.getText()));
            theproduct.setQuantity(Integer.valueOf(quantityTxt.getText()));
//            theproduct.setdDate(dDate);
//            theproduct.seteDate(eDate);
            theproduct.setCp(Integer.valueOf(cpTxt.getText()));
            theproduct.setSp(Integer.valueOf(spTxt.getText()));

            Products productObj = service.registerProduct(theproduct);

            if (productObj != null) {
                JOptionPane.showMessageDialog(this, "Data Saved!");
            } else {
                JOptionPane.showMessageDialog(this, "Data not saved!");
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
     
      
    }//GEN-LAST:event_registerBtnActionPerformed

    private void selectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllBtnActionPerformed
        // Select all products
        searchSelProd jf1=new searchSelProd();
        jf1.show();
        dispose();
    }//GEN-LAST:event_selectAllBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // On the first tab
        dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // Delete product
        try{
            Registry theRegistry=LocateRegistry.getRegistry("127.0.0.1",5000);
            ProductService service=(ProductService) theRegistry.lookup("product");
            Products theproduct =new Products();
//            theproduct.setpName(pnameTxt.getText());
//              theproduct.setQuantity(Integer.valueOf(quantityTxt.getText()));
//              theproduct.setdDate(dDate);
//               theproduct.seteDate(eDate);
//                theproduct.setCp(Integer.valueOf(cpTxt.getText()));
//                theproduct.setSp(Integer.valueOf(spTxt.getText()));
                theproduct.setpId(Integer.valueOf(pidTxt.getText()));
                Products productObj=service.deleteProducts(theproduct);
                if(productObj!=null){
                    JOptionPane.showMessageDialog(this, "Data delted Successfully!");
                }else{
                    JOptionPane.showMessageDialog(this, "Data not deleted!");
                }
          //  theproduct.setQuantity(quantityTxt.getText());
        }catch(Exception ex){
           ex.printStackTrace();
        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // Update Product
               SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//    String dDate = sdf.format(ddateTxt.getDate());
//      String eDate = sdf.format(edateTxt.getDate());
        try{
            Registry theRegistry=LocateRegistry.getRegistry("127.0.0.1",5000);
            ProductService service=(ProductService) theRegistry.lookup("product");
            Products theproduct =new Products();
            theproduct.setpName(pnameTxt.getText());
              theproduct.setQuantity(Integer.valueOf(quantityTxt.getText()));
//              theproduct.setdDate(dDate);
//               theproduct.seteDate(eDate);
                theproduct.setCp(Integer.valueOf(cpTxt.getText()));
                theproduct.setSp(Integer.valueOf(spTxt.getText()));
                theproduct.setpId(Integer.valueOf(pidTxt.getText()));
                Products productObj=service.updateProducts(theproduct);
                if(productObj!=null){
                    JOptionPane.showMessageDialog(this, "Data Updated!");
                }else{
                    JOptionPane.showMessageDialog(this, "Data not Updates!");
                }
          //  theproduct.setQuantity(quantityTxt.getText());
        }catch(Exception ex){
           ex.printStackTrace();
        }
          
            

    }//GEN-LAST:event_updateBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // reset all product fields;
   clearFields();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void searchProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductBtnActionPerformed
        // Search product
         searchSelProd jf1=new searchSelProd();
        jf1.show();
        dispose();
    }//GEN-LAST:event_searchProductBtnActionPerformed
 private boolean nameCheck(String input){
          return  Pattern.matches("[a-zA-Z]+",input);
      }
  private boolean isInteger(String input) {
    try {
        Integer.parseInt(input);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}
        public static boolean isQuantityValid(int quantity) {
        return quantity > 0;
    }
        
    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        // TODO add your handling code here:
        // to record employees
       
     try{
           Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",5000);
           EmployeeService service=(EmployeeService) theRegistry.lookup("employee");
           Employees theemployee=new Employees(); 
            if (fnameTxt.getText().trim().isEmpty() || nameCheck((fnameTxt.getText()))==false) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }  else if (salaryTxt.getText().trim().isEmpty()  || !isInteger((salaryTxt.getText()))) {
        JOptionPane.showMessageDialog(this, "Salary is Mandatory and ID should be an integer", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }   else if (lnameTxt.getText().trim().isEmpty() || nameCheck((lnameTxt.getText()))==false) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }   else if (dutyTxt.getText().trim().isEmpty() || nameCheck((dutyTxt.getText()))==false) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }  else if (passwordTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }  
    
    else{
           theemployee.setEfName(fnameTxt.getText());
           theemployee.setElName(lnameTxt.getText());
           theemployee.setDuty(dutyTxt.getText());
          //  sObj.setCp(Integer.valueOf(cpTxt.getText()));
            theemployee.setSalary(Integer.valueOf(salaryTxt.getText()));
           theemployee.setPassword(passwordTxt.getText());
           Admin theAdmin=(Admin) admincombo.getSelectedItem();
           Set<Products> productSet=new HashSet<>();
           List<Products> productsList=productListItem.getSelectedValuesList();
            for(Products theProduct : productsList){
                productSet.add(theProduct);
            }
    
           theemployee.setAdmin(theAdmin);
           theemployee.setProducts(productSet);
           Employees emplObj=service.registerEmployee(theemployee);
           if(emplObj!=null){
               JOptionPane.showMessageDialog(this, "Data Saved");
           }else{
                JOptionPane.showMessageDialog(this, "Data not Saved");
           }}
           //put products configuration
        }catch(Exception ex){
           ex.printStackTrace();
        }
     

    }//GEN-LAST:event_regBtnActionPerformed

    private void selAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selAllBtnActionPerformed
        // TODO add your handling code here:
          searchSelEmp jf1=new searchSelEmp();
        jf1.show();
        dispose();
      
    }//GEN-LAST:event_selAllBtnActionPerformed

    private void logOuTEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOuTEBtnActionPerformed
        // on tab 2
        dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_logOuTEBtnActionPerformed

    private void SearchETxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchETxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchETxtActionPerformed

    private void updTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updTxtActionPerformed
        // Update Employees
       
           try{
           Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",5000);
           EmployeeService service=(EmployeeService) theRegistry.lookup("employee");
           Employees theemployee=new Employees();
               if (fnameTxt.getText().trim().isEmpty() || nameCheck((fnameTxt.getText()))==false) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }  else if (salaryTxt.getText().trim().isEmpty()  || !isInteger((salaryTxt.getText()))) {
        JOptionPane.showMessageDialog(this, "Salary is Mandatory and ID should be an integer", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }   else if (lnameTxt.getText().trim().isEmpty() || nameCheck((lnameTxt.getText()))==false) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }   else if (dutyTxt.getText().trim().isEmpty() || nameCheck((dutyTxt.getText()))==false) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }  else if (passwordTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, " name is Mandatory and Name should be a string", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    }  
    
    else{
           theemployee.setEfName(fnameTxt.getText());
           theemployee.setElName(lnameTxt.getText());
           theemployee.setDuty(dutyTxt.getText());
           theemployee.setEid(Integer.valueOf(SearchETxt.getText()));
          //  sObj.setCp(Integer.valueOf(cpTxt.getText()));
            theemployee.setSalary(Integer.valueOf(salaryTxt.getText()));
           theemployee.setPassword(passwordTxt.getText());
           Admin theAdmin=(Admin) admincombo.getSelectedItem();
           Set<Products> productSet=new HashSet<>();
           List<Products> productsList=productListItem.getSelectedValuesList();
            for(Products theProduct : productsList){
                productSet.add(theProduct);
            }
            
           theemployee.setAdmin(theAdmin);
           theemployee.setProducts(productSet);
           Employees emplObj=service.updateEmployees(theemployee);
           if(emplObj!=null){
               JOptionPane.showMessageDialog(this, "Data Updated");
           }else{
                JOptionPane.showMessageDialog(this, "Data not Updated");
           }}
           //put products configuration
        }catch(Exception ex){
           ex.printStackTrace();
        }

    }//GEN-LAST:event_updTxtActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // delete Employee
          try{
           Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",5000);
           EmployeeService service=(EmployeeService) theRegistry.lookup("employee");
           Employees theemployee=new Employees(); 
         if (SearchETxt.getText().trim().isEmpty() ) {
        JOptionPane.showMessageDialog(this, " ID to search is mandatory", "Field Mandatory", JOptionPane.WARNING_MESSAGE);
    } else{
           theemployee.setEid(Integer.valueOf(SearchETxt.getText()));
  
           Employees emplObj=service.deleteEmployees(theemployee);
           if(emplObj!=null){
               JOptionPane.showMessageDialog(this, "Data delete");
           }else{
                JOptionPane.showMessageDialog(this, "Data not delete,please enter a valid ID");
           }
           //put products configuration
        }}catch(Exception ex){
           ex.printStackTrace();
        }
clearFields();
    }//GEN-LAST:event_delBtnActionPerformed

    private void resetEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEBtnActionPerformed
        // Reset Employee Data
        clearFields();
    }//GEN-LAST:event_resetEBtnActionPerformed
private void clearFields() {
    fnameTxt.setText("");
    lnameTxt.setText("");
    salaryTxt.setText("");
    dutyTxt.setText("");
    passwordTxt.setText("");
    adidTxt.setText("");
    namesTxt.setText("");
    usernameTxt.setText("");
    passwordTxt.setText("");
      dateTxt.setDate(null);
      updatesTxt.setText("");
       pnameTxt.setText("");
        quantityTxt.setText("");
//      ddateTxt.setDate(null);
//       edateTxt.setDate(null);
         cpTxt.setText("");
           spTxt.setText("");
       
    // Add more fields if needed

    // Set focus to the first field after clearing
    fnameTxt.requestFocus();
}
    private void searchEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEBtnActionPerformed
searchSelProd jf1=new searchSelProd();
        jf1.show();
        dispose();
//        searchSelEmp jf1=new searchSelEmp();
//        jf1.show();
//        dispose();

        //          if (SearchETxt.getText().trim().isEmpty()) {
            //        JOptionPane.showMessageDialog(this, "Employee ID to search is mandatory");
            //    } else {
            //        try {
                //            int employeeId = Integer.parseInt(SearchETxt.getText());
                //
                //            StockModel sObj = new StockModel();
                //            sObj.setEid(employeeId);  // Set the Employee ID for searching
                //
                //            StockDao dao = new StockDao();
                //            StockModel sm = dao.searchEmployee(sObj);
                //
                //            if (sm != null) {
                    //                firstNameTxt.setText(sm.getEfname());
                    //                lastNameTxt.setText(sm.getElname());
                    //                dutyTxt.setText(sm.getDuty());
                    //                 // salaryTxt.setText(sm.getSalary().toString());
                    //                // Salary should be added here
                    //                 //salaryTxt.setText(sm.salaryTxt());
                    //                passwordTxt.setText(sm.getPassword());
                    //                // Set the retrieved salary wherever needed
                    //            } else {
                    //                JOptionPane.showMessageDialog(this, "Employee not Found");
                    //                        clearEmployeeFields();
                    //
                    //            }
                //        } catch (NumberFormatException ex) {
                //            JOptionPane.showMessageDialog(this, "Invalid Employee ID format");
                //        }
            //    }

    }//GEN-LAST:event_searchEBtnActionPerformed

    private void searchAdmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdmBtnActionPerformed
        // to search Admin
             if (searchidTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Admin ID to search is mandatory");
    } else {
        try {
           // int adminId = Integer.parseInt(searchAdmTxt.getText());
            String adminId=  searchidTxt.getText();
            
            Stocklog2 sObj = new Stocklog2();
            sObj.setADID(adminId);  

            Stocklog dao = new Stocklog();
            Stocklog2 sm = dao.searchAdmin(sObj);

            if (sm != null) {
                adidTxt.setText(sm.getADID());
                namesTxt.setText(sm.getNames());
                usernameTxt.setText(sm.getAdusername());
                  admPassTxt.setText(sm.getAdpassword());
              
                // Set the retrieved salary wherever needed
            } else {
                JOptionPane.showMessageDialog(this, "Admin ID not Found");
                      

            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid admin ID format");
        }
             }
    }//GEN-LAST:event_searchAdmBtnActionPerformed

    private void logoutAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAdmActionPerformed
        // third tab
        dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_logoutAdmActionPerformed

    private void regAdmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAdmBtnActionPerformed
        // Register admin
        
          try{
            Registry theRegistry=LocateRegistry.getRegistry("127.0.0.1", 5000);
            AdminService service=(AdminService) theRegistry.lookup("admin");
            Admin theAdmin=new Admin();
//              if(adidTxt.getText().trim().isEmpty()||adidTxt.getText().length() == 3){
//            JOptionPane.showMessageDialog(this, "Admin id is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
//        }else
                  if(namesTxt.getText().trim().isEmpty()|| nameCheck((namesTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "Name is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(usernameTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(admPassTxt.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Password is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        } else{
            theAdmin.setNames(namesTxt.getText());
            theAdmin.setADID(adidTxt.getText());
            theAdmin.setAdUsername(usernameTxt.getText());
            theAdmin.setAdPassword(passwordTxt.getText());
            Admin adminObj=service.registerAdmin(theAdmin);
            if(adminObj!=null){
                JOptionPane.showMessageDialog(this, "Data saved!");
            }else{
                JOptionPane.showMessageDialog(this, "Data not saved");
            }}
        }catch(Exception ex){
              ex.printStackTrace();
        }

    }//GEN-LAST:event_regAdmBtnActionPerformed

    private void updAdmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updAdmTxtActionPerformed
        try{
            Registry theRegistry=LocateRegistry.getRegistry("127.0.0.1", 5000);
            AdminService service=(AdminService) theRegistry.lookup("admin");
            Admin theAdmin=new Admin();
                 if(adidTxt.getText().trim().isEmpty()||adidTxt.getText().length() == 3){
            JOptionPane.showMessageDialog(this, "Admin id is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(namesTxt.getText().trim().isEmpty()|| nameCheck((namesTxt.getText()))==false){
            JOptionPane.showMessageDialog(this, "Name is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(usernameTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        }else if(admPassTxt.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(this, "Password is Mandatory","Field Mandatory",JOptionPane.WARNING_MESSAGE);
        } else{
            theAdmin.setNames(namesTxt.getText());
            theAdmin.setADID(adidTxt.getText());
            theAdmin.setAdUsername(usernameTxt.getText());
            theAdmin.setAdPassword(passwordTxt.getText());
            Admin adminObj=service.updateAdmin(theAdmin);
            if(adminObj!=null){
                JOptionPane.showMessageDialog(this, "Data updated!");
            }else{
                JOptionPane.showMessageDialog(this, "Data not updated");
            }}
        }catch(Exception ex){
              ex.printStackTrace();
        }   

    }//GEN-LAST:event_updAdmTxtActionPerformed

    private void delAdmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAdmTxtActionPerformed
        // Delete Admin
          try{
            Registry theRegistry=LocateRegistry.getRegistry("127.0.0.1", 5000);
            AdminService service=(AdminService) theRegistry.lookup("admin");
            Admin theAdmin=new Admin();
            theAdmin.setNames(namesTxt.getText());
            theAdmin.setADID(adidTxt.getText());
            theAdmin.setAdUsername(usernameTxt.getText());
            theAdmin.setAdPassword(passwordTxt.getText());
            Admin adminObj=service.deleteAdmin(theAdmin);
            if(adminObj!=null){
                JOptionPane.showMessageDialog(this, "Data deleted!");
            }else{
                JOptionPane.showMessageDialog(this, "Data not daleted");
            }
        }catch(Exception ex){
              ex.printStackTrace();
        }

    }//GEN-LAST:event_delAdmTxtActionPerformed

    private void seleAlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleAlBtnActionPerformed
        // TODO add your handling code here:
          searchSelAdmin jf1=new searchSelAdmin();
        jf1.show();
        dispose();
      
    }//GEN-LAST:event_seleAlBtnActionPerformed

    private void resetABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetABtnActionPerformed
        // Reset Admin Information
         clearFields();
       
    }//GEN-LAST:event_resetABtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //  Updates or information to Employees
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          String eDate = sdf.format(dateTxt.getDate());
         try{
            Registry theRegistry=LocateRegistry.getRegistry("127.0.0.1", 5000);
            UpdatesService service=(UpdatesService) theRegistry.lookup("update");
            Updates theUpdates=new Updates();
            theUpdates.setWorkUpdates(updatesTxt.getText());
            theUpdates.setDate(eDate);
          //  Admin selectedAdmin=(Admin) adminsCombo.getSelectedItem();
            //theUpdates.setAdmin(selectedAdmin);
            
            Updates updateObj=service.registerUpdate(theUpdates);
            if(updateObj!=null){
                JOptionPane.showMessageDialog(this, "Data saved!");
            }else{
                JOptionPane.showMessageDialog(this, "Data not saved");
            }
        }catch(Exception ex){
              ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Button clicked to see employees opinions
        opinions jf2=new opinions();
        jf2.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void uplogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplogoutBtnActionPerformed
        // last tab
        dashboard jf1=new dashboard();
        jf1.show();
        dispose();
    }//GEN-LAST:event_uplogoutBtnActionPerformed

    private void resetUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetUpdActionPerformed
        // TODO add your handling code here:
 
         clearFields();
    }//GEN-LAST:event_resetUpdActionPerformed

    private void quantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void dutyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dutyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dutyTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void lnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTxtActionPerformed

    private void pidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidTxtActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
          searchSelEmp jf1=new searchSelEmp();
        jf1.show();
        dispose();
      
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchETxt;
    private javax.swing.JTextField adidTxt;
    private javax.swing.JPasswordField admPassTxt;
    private javax.swing.JComboBox<Admin> admincombo;
    private javax.swing.JLabel bImageTxt;
    private javax.swing.JTextField cpTxt;
    private com.toedter.calendar.JDateChooser dateTxt;
    private javax.swing.JButton delAdmTxt;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dutyTxt;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JButton logOuTEBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton logoutAdm;
    private javax.swing.JTextField namesTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField pidTxt;
    private javax.swing.JTextField pnameTxt;
    private javax.swing.JButton print;
    private javax.swing.JList<Products> productListItem;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton regAdmBtn;
    private javax.swing.JButton regBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resetABtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton resetEBtn;
    private javax.swing.JButton resetUpd;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JButton searchAdmBtn;
    private javax.swing.JButton searchEBtn;
    private javax.swing.JButton searchProductBtn;
    private javax.swing.JTextField searchidTxt;
    private javax.swing.JButton selAllBtn;
    private javax.swing.JButton seleAlBtn;
    private javax.swing.JButton selectAllBtn;
    private javax.swing.JTextField spTxt;
    private javax.swing.JButton updAdmTxt;
    private javax.swing.JButton updTxt;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextArea updatesTxt;
    private javax.swing.JButton uplogoutBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
